// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6_DSQwiPJvH_dapamy7-r0pzAky7mtCI',
    appId: '1:360206178275:web:a2b79d4297514bdf40f2d6',
    messagingSenderId: '360206178275',
    projectId: 'sarmadi-ai',
    authDomain: 'sarmadi-ai.firebaseapp.com',
    storageBucket: 'sarmadi-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg4dLiDGKb4uKimJDBhuEL84D8irZM8sk',
    appId: '1:360206178275:android:a978a5678344538840f2d6',
    messagingSenderId: '360206178275',
    projectId: 'sarmadi-ai',
    storageBucket: 'sarmadi-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuPoImUcKZzXgX_OggrexXzx5HQcZ4YhE',
    appId: '1:360206178275:ios:8cb4e9f3f4ed1ef440f2d6',
    messagingSenderId: '360206178275',
    projectId: 'sarmadi-ai',
    storageBucket: 'sarmadi-ai.appspot.com',
    androidClientId: '360206178275-45pr8egccgodst1kcs3r25p8pi759ag7.apps.googleusercontent.com',
    iosClientId: '360206178275-euht05ojmr3oupd3cd5g0mb4ef1lhaih.apps.googleusercontent.com',
    iosBundleId: 'com.example.sarmadi',
  );
}
